import type { CurriculumMapItem } from "../types";

export const cambodiaMoeysCurriculumMap: CurriculumMapItem[] = [
  {
    curriculum: "moeys",
    grade: "grade-2",
    subject: "math",
    strand: "Numbers and Operations",
    topic: "Counting and Number Order",
    learningOutcome: "Read, write, order, and compare whole numbers up to 100.",
    difficultySuggestion: "easy",
  },
  {
    curriculum: "moeys",
    grade: "grade-2",
    subject: "math",
    strand: "Numbers and Operations",
    topic: "Addition and Subtraction",
    learningOutcome: "Solve addition and subtraction problems within 100 using concrete examples and number sentences.",
    difficultySuggestion: "easy",
  },
  {
    curriculum: "moeys",
    grade: "grade-3",
    subject: "math",
    strand: "Numbers and Operations",
    topic: "Multiplication",
    learningOutcome: "Use repeated addition and equal groups to understand multiplication facts.",
    difficultySuggestion: "medium",
  },
  {
    curriculum: "moeys",
    grade: "grade-3",
    subject: "math",
    strand: "Measurement",
    topic: "Time",
    learningOutcome: "Read clocks to the hour and half hour and solve simple time questions.",
    difficultySuggestion: "easy",
  },
  {
    curriculum: "moeys",
    grade: "grade-4",
    subject: "math",
    strand: "Numbers and Operations",
    topic: "Division",
    learningOutcome: "Solve division problems using equal sharing, grouping, and basic division facts.",
    difficultySuggestion: "medium",
  },
  {
    curriculum: "moeys",
    grade: "grade-4",
    subject: "math",
    strand: "Geometry",
    topic: "Perimeter",
    learningOutcome: "Find the perimeter of simple rectangles and shapes drawn on a grid.",
    difficultySuggestion: "medium",
  },
  {
    curriculum: "moeys",
    grade: "grade-5",
    subject: "math",
    strand: "Numbers and Operations",
    topic: "Fractions",
    learningOutcome: "Compare fractions with the same denominator and relate fractions to parts of a whole.",
    difficultySuggestion: "medium",
  },
  {
    curriculum: "moeys",
    grade: "grade-5",
    subject: "math",
    strand: "Data",
    topic: "Charts and Graphs",
    learningOutcome: "Read simple charts and graphs and use the data to answer comparison questions.",
    difficultySuggestion: "medium",
  },
];
