import type { CurriculumMapItem } from "../types";

export const cambridgeCurriculumMap: CurriculumMapItem[] = [
  {
    curriculum: "cambridge",
    grade: "grade-2",
    subject: "math",
    strand: "Number",
    topic: "Place Value",
    learningOutcome: "Identify the value of each digit in a two-digit number and compare numbers up to 100.",
    difficultySuggestion: "easy",
  },
  {
    curriculum: "cambridge",
    grade: "grade-2",
    subject: "math",
    strand: "Calculation",
    topic: "Addition and Subtraction",
    learningOutcome: "Solve one-step addition and subtraction problems within 100 using mental and written methods.",
    difficultySuggestion: "easy",
  },
  {
    curriculum: "cambridge",
    grade: "grade-3",
    subject: "math",
    strand: "Number",
    topic: "Multiplication and Division",
    learningOutcome: "Use multiplication facts for 2, 5, and 10 to solve simple division and grouping problems.",
    difficultySuggestion: "medium",
  },
  {
    curriculum: "cambridge",
    grade: "grade-3",
    subject: "math",
    strand: "Measure",
    topic: "Length and Mass",
    learningOutcome: "Choose suitable units and compare everyday measurements of length and mass.",
    difficultySuggestion: "easy",
  },
  {
    curriculum: "cambridge",
    grade: "grade-4",
    subject: "math",
    strand: "Number",
    topic: "Fractions",
    learningOutcome: "Recognize unit and non-unit fractions and compare simple fractions with the same denominator.",
    difficultySuggestion: "medium",
  },
  {
    curriculum: "cambridge",
    grade: "grade-4",
    subject: "math",
    strand: "Geometry",
    topic: "Angles and Shapes",
    learningOutcome: "Identify right angles and describe common properties of 2D shapes.",
    difficultySuggestion: "medium",
  },
  {
    curriculum: "cambridge",
    grade: "grade-5",
    subject: "math",
    strand: "Number",
    topic: "Decimals",
    learningOutcome: "Read, write, and compare decimals up to two decimal places in everyday contexts.",
    difficultySuggestion: "medium",
  },
  {
    curriculum: "cambridge",
    grade: "grade-5",
    subject: "math",
    strand: "Data Handling",
    topic: "Tables and Charts",
    learningOutcome: "Interpret information from tables and bar charts to answer one-step and two-step questions.",
    difficultySuggestion: "medium",
  },
];
